/**
 * This class is generated by jOOQ
 */
package jooq;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in PUBLIC
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_7DA5000A_206C_46AD_AF7E_8851BBAFBDEA</code>
     */
    public static final Sequence<Long> SYSTEM_SEQUENCE_7DA5000A_206C_46AD_AF7E_8851BBAFBDEA = new SequenceImpl<Long>("SYSTEM_SEQUENCE_7DA5000A_206C_46AD_AF7E_8851BBAFBDEA", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_F00F25BB_2029_4E20_BF23_0C6EA0DCAC46</code>
     */
    public static final Sequence<Long> SYSTEM_SEQUENCE_F00F25BB_2029_4E20_BF23_0C6EA0DCAC46 = new SequenceImpl<Long>("SYSTEM_SEQUENCE_F00F25BB_2029_4E20_BF23_0C6EA0DCAC46", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);
}
