/**
 * This class is generated by jOOQ
 */
package jooq;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in PUBLIC
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_616D8C3D_B284_465F_9FA5_E0DD3610DD09</code>
     */
    public static final Sequence<Long> SYSTEM_SEQUENCE_616D8C3D_B284_465F_9FA5_E0DD3610DD09 = new SequenceImpl<Long>("SYSTEM_SEQUENCE_616D8C3D_B284_465F_9FA5_E0DD3610DD09", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_A861B386_7718_435F_9211_D8C684A8BB4D</code>
     */
    public static final Sequence<Long> SYSTEM_SEQUENCE_A861B386_7718_435F_9211_D8C684A8BB4D = new SequenceImpl<Long>("SYSTEM_SEQUENCE_A861B386_7718_435F_9211_D8C684A8BB4D", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);
}
