/**
 * This class is generated by jOOQ
 */
package jooq.tables.records;


import javax.annotation.Generated;

import jooq.tables.Todo;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TodoRecord extends UpdatableRecordImpl<TodoRecord> implements Record5<Long, String, Boolean, Integer, Long> {

    private static final long serialVersionUID = 848427648;

    /**
     * Setter for <code>PUBLIC.TODO.TODO_ID</code>.
     */
    public void setTodoId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.TODO.TODO_ID</code>.
     */
    public Long getTodoId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>PUBLIC.TODO.TITLE</code>.
     */
    public void setTitle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.TODO.TITLE</code>.
     */
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>PUBLIC.TODO.COMPLETED</code>.
     */
    public void setCompleted(Boolean value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.TODO.COMPLETED</code>.
     */
    public Boolean getCompleted() {
        return (Boolean) get(2);
    }

    /**
     * Setter for <code>PUBLIC.TODO.ORDER</code>.
     */
    public void setOrder(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.TODO.ORDER</code>.
     */
    public Integer getOrder() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>PUBLIC.TODO.USER_ID</code>.
     */
    public void setUserId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>PUBLIC.TODO.USER_ID</code>.
     */
    public Long getUserId() {
        return (Long) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Long, String, Boolean, Integer, Long> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Long, String, Boolean, Integer, Long> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Todo.TODO.TODO_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Todo.TODO.TITLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field3() {
        return Todo.TODO.COMPLETED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Todo.TODO.ORDER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return Todo.TODO.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getTodoId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value3() {
        return getCompleted();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getOrder();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TodoRecord value1(Long value) {
        setTodoId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TodoRecord value2(String value) {
        setTitle(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TodoRecord value3(Boolean value) {
        setCompleted(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TodoRecord value4(Integer value) {
        setOrder(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TodoRecord value5(Long value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TodoRecord values(Long value1, String value2, Boolean value3, Integer value4, Long value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TodoRecord
     */
    public TodoRecord() {
        super(Todo.TODO);
    }

    /**
     * Create a detached, initialised TodoRecord
     */
    public TodoRecord(Long todoId, String title, Boolean completed, Integer order, Long userId) {
        super(Todo.TODO);

        set(0, todoId);
        set(1, title);
        set(2, completed);
        set(3, order);
        set(4, userId);
    }
}
